#pragma once
#include "Apostle.h"

#ifdef GLFW_WINDOWING_SYSTEM 

namespace Apostle
{
	/*Key values for GLFW Windowing API*/
	enum class KEYCODES : int
	{
		APOSTLE_KEY_NONE = -1, /*None*/
		APOSTLE_KEY_SPACE = GLFW_KEY_SPACE,
		APOSTLE_KEY_APOSTROPHE = GLFW_KEY_SPACE,  /* ' */
		APOSTLE_KEY_COMMA = GLFW_KEY_COMMA,  /* , */
		APOSTLE_KEY_MINUS = GLFW_KEY_MINUS,  /* - */
		APOSTLE_KEY_PERIOD = GLFW_KEY_PERIOD,  /* . */
		APOSTLE_KEY_SLASH = GLFW_KEY_SLASH,  /* / */
		APOSTLE_KEY_0 = GLFW_KEY_0,
		APOSTLE_KEY_1 = GLFW_KEY_1,
		APOSTLE_KEY_2 = GLFW_KEY_2,
		APOSTLE_KEY_3 = GLFW_KEY_3,
		APOSTLE_KEY_4 = GLFW_KEY_4,
		APOSTLE_KEY_5 = GLFW_KEY_5,
		APOSTLE_KEY_6 = GLFW_KEY_6,
		APOSTLE_KEY_7 = GLFW_KEY_7,
		APOSTLE_KEY_8 = GLFW_KEY_8,
		APOSTLE_KEY_9 = GLFW_KEY_9,
		APOSTLE_KEY_SEMICOLON = GLFW_KEY_SEMICOLON,  /* ; */
		APOSTLE_KEY_EQUAL = GLFW_KEY_EQUAL,  /* = */
		APOSTLE_KEY_A = GLFW_KEY_A,
		APOSTLE_KEY_B = GLFW_KEY_B,
		APOSTLE_KEY_C = GLFW_KEY_C,
		APOSTLE_KEY_D = GLFW_KEY_D,
		APOSTLE_KEY_E = GLFW_KEY_E,
		APOSTLE_KEY_F = GLFW_KEY_F,
		APOSTLE_KEY_G = GLFW_KEY_G,
		APOSTLE_KEY_H = GLFW_KEY_H,
		APOSTLE_KEY_I = GLFW_KEY_I,
		APOSTLE_KEY_J = GLFW_KEY_J,
		APOSTLE_KEY_K = GLFW_KEY_K,
		APOSTLE_KEY_L = GLFW_KEY_L,
		APOSTLE_KEY_M = GLFW_KEY_M,
		APOSTLE_KEY_N = GLFW_KEY_N,
		APOSTLE_KEY_O = GLFW_KEY_O,
		APOSTLE_KEY_P = GLFW_KEY_P,
		APOSTLE_KEY_Q = GLFW_KEY_Q,
		APOSTLE_KEY_R = GLFW_KEY_R,
		APOSTLE_KEY_S = GLFW_KEY_S,
		APOSTLE_KEY_T = GLFW_KEY_T,
		APOSTLE_KEY_U = GLFW_KEY_U,
		APOSTLE_KEY_V = GLFW_KEY_V,
		APOSTLE_KEY_W = GLFW_KEY_W,
		APOSTLE_KEY_X = GLFW_KEY_X,
		APOSTLE_KEY_Y = GLFW_KEY_Y,
		APOSTLE_KEY_Z = GLFW_KEY_Z,
		APOSTLE_KEY_LEFT_BRACKET = GLFW_KEY_LEFT_BRACKET,  /* [ */
		APOSTLE_KEY_BACKSLASH = GLFW_KEY_BACKSLASH,  /* \ */
		APOSTLE_KEY_RIGHT_BRACKET = GLFW_KEY_RIGHT_BRACKET,  /* ] */
		APOSTLE_KEY_GRAVE_ACCENT = GLFW_KEY_GRAVE_ACCENT,  /* ` */
		APOSTLE_KEY_WORLD_1 = GLFW_KEY_WORLD_1, /* non-US*/

		/* Function keys */
		APOSTLE_KEY_ESCAPE = GLFW_KEY_ESCAPE,
		APOSTLE_KEY_ENTER = GLFW_KEY_ENTER,
		APOSTLE_KEY_TAB = GLFW_KEY_TAB,
		APOSTLE_KEY_BACKSPACE = GLFW_KEY_BACKSPACE,
		APOSTLE_KEY_INSERT = GLFW_KEY_INSERT,
		APOSTLE_KEY_DELETE = GLFW_KEY_DELETE,
		APOSTLE_KEY_RIGHT = GLFW_KEY_RIGHT,
		APOSTLE_KEY_LEFT = GLFW_KEY_LEFT,
		APOSTLE_KEY_DOWN = 264,
		APOSTLE_KEY_UP = 265,
		APOSTLE_KEY_PAGE_UP = 266,
		APOSTLE_KEY_PAGE_DOWN = 267,
		APOSTLE_KEY_HOME = 268,
		APOSTLE_KEY_END = 269,
		APOSTLE_KEY_CAPS_LOCK = 280,
		APOSTLE_KEY_SCROLL_LOCK = 281,
		APOSTLE_KEY_NUM_LOCK = 282,
		APOSTLE_KEY_PRINT_SCREEN = 283,
		APOSTLE_KEY_PAUSE = 284,
		APOSTLE_KEY_F1 = GLFW_KEY_F1,
		APOSTLE_KEY_F2 = GLFW_KEY_F2,
		APOSTLE_KEY_F3 = GLFW_KEY_F3,
		APOSTLE_KEY_F4 = GLFW_KEY_F4,
		APOSTLE_KEY_F5 = GLFW_KEY_F5,
		APOSTLE_KEY_F6 = GLFW_KEY_F6,
		APOSTLE_KEY_F7 = GLFW_KEY_F7,
		APOSTLE_KEY_F8 = GLFW_KEY_F8,
		APOSTLE_KEY_F9 = GLFW_KEY_F9,
		APOSTLE_KEY_F10 = GLFW_KEY_F10,
		APOSTLE_KEY_F11 = GLFW_KEY_F11,
		APOSTLE_KEY_F12 = GLFW_KEY_F12,
		APOSTLE_KEY_F13 = GLFW_KEY_F13,
		APOSTLE_KEY_F14 = GLFW_KEY_F14,
		APOSTLE_KEY_F15 = GLFW_KEY_F15,
		APOSTLE_KEY_F16 = GLFW_KEY_F16,
		APOSTLE_KEY_F17 = GLFW_KEY_F17,
		APOSTLE_KEY_F18 = GLFW_KEY_F18,
		APOSTLE_KEY_F19 = GLFW_KEY_F19,
		APOSTLE_KEY_F20 = GLFW_KEY_F20,
		APOSTLE_KEY_F21 = GLFW_KEY_F21,
		APOSTLE_KEY_F22 = GLFW_KEY_F22,
		APOSTLE_KEY_F23 = GLFW_KEY_F23,
		APOSTLE_KEY_F24 = GLFW_KEY_F24,
		APOSTLE_KEY_F25 = GLFW_KEY_F25,
		APOSTLE_KEY_KP_0 = GLFW_KEY_KP_0,
		APOSTLE_KEY_KP_1 = GLFW_KEY_KP_1,
		APOSTLE_KEY_KP_2 = GLFW_KEY_KP_2,
		APOSTLE_KEY_KP_3 = GLFW_KEY_KP_3,
		APOSTLE_KEY_KP_4 = GLFW_KEY_KP_4,
		APOSTLE_KEY_KP_5 = GLFW_KEY_KP_5,
		APOSTLE_KEY_KP_6 = GLFW_KEY_KP_6,
		APOSTLE_KEY_KP_7 = GLFW_KEY_KP_7,
		APOSTLE_KEY_KP_8 = GLFW_KEY_KP_8,
		APOSTLE_KEY_KP_9 = GLFW_KEY_KP_9,
		APOSTLE_KEY_KP_DECIMAL = GLFW_KEY_KP_DECIMAL,
		APOSTLE_KEY_KP_DIVIDE = GLFW_KEY_KP_DIVIDE,
		APOSTLE_KEY_KP_MULTIPLY = GLFW_KEY_KP_MULTIPLY,
		APOSTLE_KEY_KP_SUBTRACT = GLFW_KEY_KP_SUBTRACT,
		APOSTLE_KEY_KP_ADD = GLFW_KEY_KP_ADD,
		APOSTLE_KEY_KP_ENTER = GLFW_KEY_KP_ENTER,
		APOSTLE_KEY_KP_EQUAL = GLFW_KEY_KP_EQUAL,
		APOSTLE_KEY_LEFT_SHIFT = GLFW_KEY_LEFT_SHIFT,
		APOSTLE_KEY_LEFT_CONTROL = GLFW_KEY_LEFT_CONTROL,
		APOSTLE_KEY_LEFT_ALT = GLFW_KEY_LEFT_ALT,
		APOSTLE_KEY_LEFT_SUPER = GLFW_KEY_LEFT_SUPER,
		APOSTLE_KEY_RIGHT_SHIFT = GLFW_KEY_RIGHT_SHIFT,
		APOSTLE_KEY_RIGHT_CONTROL = GLFW_KEY_RIGHT_CONTROL,
		APOSTLE_KEY_RIGHT_ALT = GLFW_KEY_RIGHT_ALT,
		APOSTLE_KEY_RIGHT_SUPER = GLFW_KEY_RIGHT_SUPER,
		APOSTLE_KEY_MENU = GLFW_KEY_MENU,

		APOSTLE_KEY_LAST = APOSTLE_KEY_MENU,
	};


	/*Defining Mouse values for GLFW Windowing API/*/
	enum class MOUSEBUTTONCODES : int
	{
		APOSTLE_MOUSE_BUTTON_NONE = -1,
		APOSTLE_MOUSE_BUTTON_1 = GLFW_MOUSE_BUTTON_1,
		APOSTLE_MOUSE_BUTTON_2 = GLFW_MOUSE_BUTTON_2,
		APOSTLE_MOUSE_BUTTON_3 = GLFW_MOUSE_BUTTON_3,
		APOSTLE_MOUSE_BUTTON_4 = GLFW_MOUSE_BUTTON_4,
		APOSTLE_MOUSE_BUTTON_5 = GLFW_MOUSE_BUTTON_5,
		APOSTLE_MOUSE_BUTTON_6 = GLFW_MOUSE_BUTTON_6,
		APOSTLE_MOUSE_BUTTON_7 = GLFW_MOUSE_BUTTON_7,
		APOSTLE_MOUSE_BUTTON_8 = GLFW_MOUSE_BUTTON_8,
		APOSTLE_BUTTON_LAST = APOSTLE_MOUSE_BUTTON_8,
		APOSTLE_BUTTON_LEFT = APOSTLE_MOUSE_BUTTON_1,
		APOSTLE_BUTTON_RIGHT = APOSTLE_MOUSE_BUTTON_2,
		APOSTLE_BUTTON_MIDDLE = APOSTLE_MOUSE_BUTTON_3
	};
}
#endif